### ISSUE TITLE
Does not fulfill official awesome list criteria

### ISSUE THREAD

**Issue by lohfu** [dhamaniasad/awesome-postgres#111]
I would like to submit your list to the official awesome list repo, but it does not currently comply with the official guidelines. Could you perhaps update it so it does?

The following conditions are not met:
```
	- [ ] contains the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- [ ] has a Table of Contents section named `Contents` as the first section,
	- [ ] has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license) *(Meaning something like CC0, NOT a code licence like MIT, BSD, Apache, etc)*,
	- [ ] has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines),
```

**Comment by dhamaniasad** [comment]
Hi @lohfu,

We do have contribution guidelines, CC0, and a table of contents. I think including the badge front and center as the first thing anyone sees after the title, that just takes attention away from the content of the list, which is what people are here for. Also, I think that being required to follow certain guidelines I do not control seems very restricting to me, and I am not comfortable with that. Hence this is not on my priority list right now, regardless thanks for reaching out.

**Comment by lohfu** [comment]
ok, seems very reasonable.

**Comment by cbbrowne** [comment]
If all that is needed to improve the publicity of the list is to add a badge, I'd say that's a hoop worth jumping through.
When I didn't see a Postgres list in the Database section, of the "master" list, I wondered why there was no such list.  I think it makes sense to go to *some* effort to get it integrated in.

**Comment by dhamaniasad** [comment]
Thanks, but I stand by my opinion. I mean no harm :).

**Comment by cbbrowne** [comment]
I think it *does* do harm to prevent inclusion in the "master" list, whether that's intended or not.

I hope you would still mean no harm if others were to submit a similarly-named fork that does comply to the "central" guidelines.  Hopefully that wouldn't lead to hard feelings?

**Comment by dhamaniasad** [comment]
I'll let other maintainers back me up here:

[```I dont think so. Each repo is the star with useful information
regarding a specific topic and it should stay that way, not clutter or
deflect attention to unrelated content - Ideally a badge or link to
external resources should be at the bottom or elsewhere pointing
people to additional resources that may be useful to them and yet
somewhat related to the main content that people came looking for.```](https://github.com/sindresorhus/awesome/issues/253#issuecomment-127855379)

[```@RichardLitt yes, I've read the issue and I am not going to include their brand mark to this repository. 
Although I have the backlink to awesome at the top of the page. I think that's enough. 
They (awesome) can always exclude the link to my list if their "brand mark" is more important than the content I am providing.```](https://github.com/dzharii/awesome-typescript/pull/9)

Also, check out this issue: https://github.com/sindresorhus/awesome/issues/253.

The really pushy and spammy nature is off-putting. If you want to include awesome-postgres in the "master" list, please go ahead, but you cannot expect this list to change itself due to that. I cannot stop you from forking this repo and including a link to the fork, though IMO it would be in bad faith.
