### ISSUE TITLE
Add Coils, a realtime framework built on postgres

### ISSUE THREAD

**Issue by zubairq** [dhamaniasad/awesome-postgres#12]
http://coils.cc/coils/index.html

**Comment by vamsee** [comment]
It looks like a web framework and it also supports Oracle, so I don't think "built on postgres" is entirely correct.

**Comment by zubairq** [comment]
Actually there is a hosted version coming which only works on Postgres due to licensing reasons. Sorry the documentation is not up to date with the the product yet.

**Comment by zubairq** [comment]
And there is a lot of Postgres specific code in there: https://github.com/zubairq/coils/blob/master/src/webapp/framework/server/systemfns.clj

**Comment by dhamaniasad** [comment]
@zubairq Coils advertises itself as a web framework for `Clojure`. There are also extensions for `MeteorJS` to make realtime apps using PostgreSQL. 

My point is that this would not be of interest to PostgreSQL users, but rather to Clojure users. I don't think that web frameworks are a good fit for this list right now. Of course, if that changes in the future, I will certainly consider Coils for inclusion in the list. 

I'll go ahead and close this issue for now.

**Comment by zubairq** [comment]
No worries. Since I wrote to you a lot has happened so we are not targeting postgres or even clojure users anymore, as Coils will be an online application builder so most people will not even know that Postgres is in the background. Thanks for your consideration anyway :)
