### ISSUE TITLE
http://www.asad.pw/awesome-postgres/ is not working for me.

### ISSUE THREAD

**Issue by ImreSamu** [dhamaniasad/awesome-postgres#161]
The link http://www.asad.pw/awesome-postgres/  gives me an error: 

```
This site can’t be reached
www.asad.pw’s server DNS address could not be found.
ERR_NAME_NOT_RESOLVED
```

**Comment by ImreSamu** [comment]
this link is working:  http://dhamaniasad.github.io/awesome-postgres/  ( but old [gh-pages](https://github.com/dhamaniasad/awesome-postgres/tree/gh-pages) version )

**Comment by dhamaniasad** [comment]
Changed the URL and updated the gh-pages branch. :)
