### ISSUE TITLE
What is the current project status?

### ISSUE THREAD

**Issue by stephane-klein** [dhamaniasad/awesome-postgres#283]
Hi,

@dhamaniasad what is the current project status?

I see no new commit since 4 months and 38 pending pull requests.

Best regards,
Stéphane

**Comment by dhamaniasad** [comment]
Hi @stephane-klein ,

Sorry, it gets hard to manage at times, this project needs more maintainers. I'll be putting up a request for that shortly.

**Comment by stephane-klein** [comment]
@dhamaniasad can I help you to maintain this project ?

**Comment by dhamaniasad** [comment]
@stephane-klein that will be greatly appreciated. If you're up for it I can give you write access

**Comment by pyramation** [comment]
🙌🏻🚀
