### ISSUE TITLE
pganalyze

### ISSUE THREAD

**Issue by williamn** [dhamaniasad/awesome-postgres#6]
I have used a pretty useful tool called [pganalyze](https://pganalyze.com) for about 2 weeks. I would like to add the link to this list. Into what category should I add?

**Comment by dhamaniasad** [comment]
Hey William!

This seems pretty similar to [pgbadger](https://github.com/dalibo/pgbadger) and [pghero](https://github.com/ankane/pghero), which are both open source. 

I have just created a `CONTRIBUTING.md` file in this repository, and I'll paste the relevant section here:
```
Must be free and open source. Must have an acknowledged open source license.
```
So while pganalyze might be awesome, on the basis of it not being open source, I think it is not fit for inclusion in this list. If enough people feel like non-open source tools should be included in this list, I am open to changing that requirement, and so for the time being, I will leave this issue open. 

Thanks for your interest and understanding, and please feel free to contribute other awesome open source tools to this repository :).

**Comment by williamn** [comment]
Hey Asad.

No problem. I must be missed the open source paragraph.

**Comment by dhamaniasad** [comment]
Hey @williamn,

Could you send in a pull request for `pganalyze`? Add a note in the description that goes `(Commercial Software)`, and I will merge it.

**Comment by williamn** [comment]
Sure

**Comment by dhamaniasad** [comment]
@williamn It seems like you sent a PR to your own repo.

**Comment by williamn** [comment]
Ah :disappointed: I guess that is what you get when try to send a PR at late night :smile: 

I have sent another PR. Please review it.

**Comment by dhamaniasad** [comment]
Thanks, merged.
