### ISSUE TITLE
Where to list specific articles not whole blogs?

### ISSUE THREAD

**Issue by basiszwo** [dhamaniasad/awesome-postgres#71]
I'd like to add the following articles to your list but I am not sure where exactly. Maybe in a separate "Articles" section?

The articles are as follows and give a very good overview what makes postgresql "better" other databases:

* https://www.compose.io/articles/what-postgresql-has-over-other-open-source-sql-databases/
* https://www.compose.io/articles/what-postgresql-has-over-other-open-source-sql-databases-part-ii/

**Comment by dhamaniasad** [comment]
You can go ahead and create a section called "Articles". But for multi-part articles, only link to the first part.
