### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by dhamaniasad** [dhamaniasad/awesome-postgres#74]
As I'm sure you might have noticed, a lot of PRs have been pending for quite some time now. As of late, I've been rather busy and while I'd love to dedicate more time to OSS projects like this repo, I'm afraid as of the moment, I'm swamped. 
Hence, I believe that some additional maintainers could do this repo a lot of good. 

If you have time and love Postgres, and would like to help maintain awesome-postgres, please feel free to comment on this issue or email me. If you have prior contributions to the list, you'll be given preference. In your comment/email, be sure to include:
*  A link to any Postgres related projects you've participated in
* If you write about Postgres, then a link to your blog.

**Comment by zeke** [comment]
CCing present and former members of the Heroku Postgres team: @hgmnz @will @gregburek @uhoh-itsmaciek @fdr @petergeoghegan @craigkerstiens

**Comment by uhoh-itsmaciek** [comment]
Thanks for thinking of me @zeke, but I'm working on non-Postgres stuff on the Heroku Data team at the moment, and I doubt I could dedicate proper attention to awesome-postgres. That said, you should definitely merge #73, @depesz's blog is awesome.

**Comment by lfittl** [comment]
@dhamaniasad I'd be happy to help out - I maintain a few Postgres related projects myself (see https://github.com/lfittl and https://pganalyze.com), have spoken at a few Postgres conferences, and love compiling lists like these and keeping them up to date.

I also run an entrepreneur focused list/wiki of resources at http://founderswiki.com/wiki/Main_Page (since a few years now)

Feel free to email me if you'd like to chat further (lukas@fittl.com). And on another note, seconded that @craigkerstiens would be a good person to add (he also runs Postgres Weekly).

**Comment by dhamaniasad** [comment]
@lfittl I've gone through your work and think you are a great fit for this list. I've added you as a collaborator :). Welcome aboard!

:+1: for @craigkerstiens

**Comment by lfittl** [comment]
@dhamaniasad Awesome, appreciate it!

I've processed all the open PRs, either merging them, or adding comments as appropriate.

Do you have any thoughts how you wanted to structure the repository further? (i.e. in terms of which groups to split links into)

Also, we might have to define some "notability" guidelines (I personally have many Postgres-related projects I feel would be too tiny to be relevant for this list), but not sure if its needed just yet.

**Comment by dhamaniasad** [comment]
@lfittl Thanks for joining, I'm really glad to have you onboard!

I think that right now, our grouping is fine, but if you have any thoughts/suggestions, I'm open to changes. And definitely, if some awesome resource comes along that is not fit for any of the existing groups, we can always create a new one. 

I think having some notability guidelines would be great. Something along the lines of:
1. Any project newer than 6 months is not open for inclusion just yet
2. Project must be well maintained, and should have a fairly regular commit history
3. Project should be able to demonstrate popularity or usage (GitHub stars, etc.). We do not want to include projects no one uses since then there is no incentive for someone else to maintain it if the original maintainer steps down. 

Let me know your thoughts.

**Comment by lfittl** [comment]
@dhamaniasad +1

Re: notability, I like your list and think that'd be a good and fair way to go about it. Do you want to codify this either in the README itself or in a separate file?

Specifically right now I'm unsure re: #47 and #50, both interesting projects, but it feels like if we applied these criteria they aren't the perfect fit at this time.

**Comment by dhamaniasad** [comment]
We could codify the notability guidelines in the CONTRIBUTING.md file. 

For #47 and #50(and other similar projects), there's two sides to the coin. 
On the one hand, we do not know much about these projects and where they're headed, and people who find out about these projects from awesome-postgres and end up relying on them could face issues in the future.
On the other hand, people will find out about these projects from awesome-postgres, which will drive up the numbers and give the authors more motivation, and the ball gets rolling. 

This is a tough decision to make, but we should not include very new projects in either case. We could leave the PRs open and reconsider the projects for inclusion at a later time.

**Comment by dhamaniasad** [comment]
I'll go ahead and close this issue now.
