### ISSUE TITLE
include to the common awesome list

### ISSUE THREAD

**Issue by olshevskiy87** [dhamaniasad/awesome-postgres#90]
hi guys!)
I would like to see this repository in the [awesome list](https://github.com/sindresorhus/awesome/blob/master/awesome.md). I think, that postgresql deserves it ) to make this possible here must be some additional elements like badge, license, contrib. guidelines etc (see [awesome manifesto](https://github.com/sindresorhus/awesome/blob/master/awesome.md) for more infomation). I could try to create some of this necessary elements, but first I want to know what do you think about it? Is this a good idea?

**Comment by olshevskiy87** [comment]
@dhamaniasad @lfittl  so, two weeks have passed - any comments?)

**Comment by dhamaniasad** [comment]
@olshevskiy87 Thanks for suggesting, but I'm not interested in adding the badge at this time. Sorry!

**Comment by olshevskiy87** [comment]
@dhamaniasad no problem, I got it.
